SELECT * FROM BOARD;
SELECT * FROM BOARD JOIN BOARD_COMMENT ON BOARD_NO=BOARD_REF;

SELECT * FROM BOARD JOIN BOARD_COMMENT ON BOARD_NO=BOARD_REF JOIN MEMBER ON USERID = BOARD_WRITER WHERE BOARD_NO=109; 

SELECT * FROM BOARD JOIN BOARD_COMMENT ON BOARD_NO=BOARD_REF LEFT JOIN MEMBER ON USERID=BOARD_WRITER WHERE BOARD_NO=109;